services:
  pkw-web:
    image: pkw-web
    container_name: pkw-web
    restart: unless-stopped
    build: .
    environment:
      - WIKI_PATH=/app/data/wiki
      - APP_PORT=8080
      - STORAGE_SECRET=${STORAGE_SECRET}
    networks:
      - hup
    volumes:
      - /mnt/HC_Volume_105122334/pkw-wiki:/app/data/wiki:ro

networks:
  hup:
    external: true
